=== allamemc/hito-individual-lenguaje-marcas/HITO INDIVIDUAL MARCAS/clientes.dtd
<!ELEMENT pedidos (ano+)>
<!ELEMENT ano (trimestre+)>
<!ATTLIST ano year CDATA #REQUIRED>
<!ELEMENT trimestre (pedido+)>
<!ATTLIST trimestre num CDATA #REQUIRED>
<!ELEMENT pedido (cliente, detalle_pedido)>
<!ELEMENT cliente (nombre, apellidos, telefono, direccion, correo, fecha_inclusion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (calle, ciudad, codigo_postal, provincia)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT fecha_inclusion (#PCDATA)>
<!ELEMENT detalle_pedido (numpedido, fecha_compra, fecha_entrega, total_facturaiva, producto+)>
<!ELEMENT numpedido (#PCDATA)>
<!ELEMENT fecha_compra (#PCDATA)>
<!ELEMENT fecha_entrega (#PCDATA)>
<!ELEMENT total_facturaiva (#PCDATA)>
<!ELEMENT producto (nombre, referencia, precio, unidades)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>

=== allamemc/hito-individual-lenguaje-marcas/HITO INDIVIDUAL MARCAS/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "clientes.dtd">
<pedidos>
  <ano year="2021">
    <trimestre num="1">
  <pedido>
    <cliente>
      <nombre>Linea</nombre>
      <apellidos>Gartsyde</apellidos>
      <telefono>+34 306 654 5260</telefono>
      <direccion>
        <calle>Brentwood</calle>
        <ciudad>Valencia</ciudad>
        <codigo_postal>46015</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>lgartsyde0@amazon.de</correo>
      <fecha_inclusion>04/11/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>2255</numpedido>
      <fecha_compra>29/01/2021</fecha_compra>
      <fecha_entrega>08/03/2021</fecha_entrega>
      <total_facturaiva>20789</total_facturaiva>
      <producto>
        <nombre>Sable</nombre>
        <referencia>Mercury</referencia>
        <precio>13058</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Nertie</nombre>
      <apellidos>Farriar</apellidos>
      <telefono>+34 652 433 9077</telefono>
      <direccion>
        <calle>Sage</calle>
        <ciudad>Zaragoza</ciudad>
        <codigo_postal>50080</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>nfarriar1@toplist.cz</correo>
      <fecha_inclusion>23/09/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>3450</numpedido>
      <fecha_compra>04/01/2021</fecha_compra>
      <fecha_entrega>25/03/2021</fecha_entrega>
      <total_facturaiva>26695</total_facturaiva>
      <producto>
        <nombre>Park Avenue</nombre>
        <referencia>Buick</referencia>
        <precio>17518</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Josh</nombre>
      <apellidos>Curneen</apellidos>
      <telefono>+34 431 310 7647</telefono>
      <direccion>
        <calle>Marquette</calle>
        <ciudad>Santander</ciudad>
        <codigo_postal>39080</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>jcurneen2@nsw.gov.au</correo>
      <fecha_inclusion>30/09/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>3457</numpedido>
      <fecha_compra>12/01/2021</fecha_compra>
      <fecha_entrega>09/03/2021</fecha_entrega>
      <total_facturaiva>24973</total_facturaiva>
      <producto>
        <nombre>Gemini</nombre>
        <referencia>Pontiac</referencia>
        <precio>11390</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Rianon</nombre>
      <apellidos>Tesimon</apellidos>
      <telefono>+34 294 228 7257</telefono>
      <direccion>
        <calle>Corben</calle>
        <ciudad>Pamplona/Iruña</ciudad>
        <codigo_postal>31015</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>rtesimon3@topsy.com</correo>
      <fecha_inclusion>12/12/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>3737</numpedido>
      <fecha_compra>18/01/2021</fecha_compra>
      <fecha_entrega>26/02/2021</fecha_entrega>
      <total_facturaiva>28730</total_facturaiva>
      <producto>
        <nombre>Jimmy</nombre>
        <referencia>GMC</referencia>
        <precio>11882</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Kalvin</nombre>
      <apellidos>Corneljes</apellidos>
      <telefono>+34 198 555 8060</telefono>
      <direccion>
        <calle>Dixon</calle>
        <ciudad>Pontevedra</ciudad>
        <codigo_postal>36156</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>kcorneljes4@discuz.net</correo>
      <fecha_inclusion>26/11/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>9449</numpedido>
      <fecha_compra>21/01/2021</fecha_compra>
      <fecha_entrega>11/03/2021</fecha_entrega>
      <total_facturaiva>20832</total_facturaiva>
      <producto>
        <nombre>LeSabre</nombre>
        <referencia>Buick</referencia>
        <precio>18060</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Lira</nombre>
      <apellidos>Primmer</apellidos>
      <telefono>+34 325 972 4456</telefono>
      <direccion>
        <calle>Warner</calle>
        <ciudad>Lugo</ciudad>
        <codigo_postal>27294</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>lprimmer5@wsj.com</correo>
      <fecha_inclusion>06/10/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>3190</numpedido>
      <fecha_compra>04/01/2021</fecha_compra>
      <fecha_entrega>12/02/2021</fecha_entrega>
      <total_facturaiva>28243</total_facturaiva>
      <producto>
        <nombre>C-MAX Hybrid</nombre>
        <referencia>Ford</referencia>
        <precio>13003</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Idell</nombre>
      <apellidos>Tesimon</apellidos>
      <telefono>+34 383 419 9701</telefono>
      <direccion>
        <calle>Mifflin</calle>
        <ciudad>Vitoria-Gasteiz</ciudad>
        <codigo_postal>01010</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>itesimon6@newsvine.com</correo>
      <fecha_inclusion>22/12/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>7504</numpedido>
      <fecha_compra>02/01/2021</fecha_compra>
      <fecha_entrega>08/03/2021</fecha_entrega>
      <total_facturaiva>25262</total_facturaiva>
      <producto>
        <nombre>Corvette</nombre>
        <referencia>Chevrolet</referencia>
        <precio>16620</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Madalyn</nombre>
      <apellidos>Sambals</apellidos>
      <telefono>+34 282 614 5303</telefono>
      <direccion>
        <calle>Eliot</calle>
        <ciudad>Murcia</ciudad>
        <codigo_postal>30005</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>msambals7@vkontakte.ru</correo>
      <fecha_inclusion>06/10/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>9894</numpedido>
      <fecha_compra>30/01/2021</fecha_compra>
      <fecha_entrega>13/02/2021</fecha_entrega>
      <total_facturaiva>29028</total_facturaiva>
      <producto>
        <nombre>Town &amp; Country</nombre>
        <referencia>Chrysler</referencia>
        <precio>12798</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Lizabeth</nombre>
      <apellidos>Elson</apellidos>
      <telefono>+34 690 543 5023</telefono>
      <direccion>
        <calle>Clemons</calle>
        <ciudad>Pamplona/Iruña</ciudad>
        <codigo_postal>31005</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>lelson8@utexas.edu</correo>
      <fecha_inclusion>08/12/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>4585</numpedido>
      <fecha_compra>10/01/2021</fecha_compra>
      <fecha_entrega>25/03/2021</fecha_entrega>
      <total_facturaiva>27424</total_facturaiva>
      <producto>
        <nombre>Suburban 1500</nombre>
        <referencia>GMC</referencia>
        <precio>11308</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Clerkclaude</nombre>
      <apellidos>Willcox</apellidos>
      <telefono>+34 378 768 5548</telefono>
      <direccion>
        <calle>Lakewood Gardens</calle>
        <ciudad>Gijon</ciudad>
        <codigo_postal>33209</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>cwillcox9@marriott.com</correo>
      <fecha_inclusion>14/11/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>8509</numpedido>
      <fecha_compra>15/01/2021</fecha_compra>
      <fecha_entrega>03/03/2021</fecha_entrega>
      <total_facturaiva>25629</total_facturaiva>
      <producto>
        <nombre>V12 Vantage</nombre>
        <referencia>Aston Martin</referencia>
        <precio>19445</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
</trimestre>
<trimestre num="2">
  <pedido>
    <cliente>
      <nombre>Amaleta</nombre>
      <apellidos>Hallibone</apellidos>
      <telefono>+34 924 318 2819</telefono>
      <direccion>
        <calle>Canary</calle>
        <ciudad>Santander</ciudad>
        <codigo_postal>39005</codigo_postal>
        <provincia>Spain</provincia>
      </direccion>
      <correo>ahallibone0@hao123.com</correo>
      <fecha_inclusion>13/09/2020</fecha_inclusion>
    </cliente>
    <detalle_pedido>
      <numpedido>8198</numpedido>
      <fecha_compra>17/04/2021</fecha_compra>
      <fecha_entrega>14/06/2021</fecha_entrega>
      <total_facturaiva>24649</total_facturaiva>
      <producto>
        <nombre>944</nombre>
        <referencia>Porsche</referencia>
        <precio>15614</precio>
        <unidades>1</unidades>
      </producto>
    </detalle_pedido>
  </pedido>
  <pedido>
    <cliente>
      <nombre>Bathsheba</nombre>
      <apellidos>Hazeldene</apellidos>
      <telefono>+34 390 658 7261</telefono>
      <direccion>
        <calle>Huxley</calle>
        <ciudad>Torrevieja</ciudad>
        <codigo_postal>03184</codigo_postal>
